layout_spectrum: 0.9589119
typography_spectrum: 0.202509
color:
  saturation: 0.8538577
  lightness: 0.2356345
  brandStrength: 0.797491
  brandColors:
    - '#FEFEFE'
    - '#818181'
    - '#F8B133'
    - '#BAB9B8'
    - '#5F5D5D'
  rhythmicContrast: 0.9041818
name: Upgrade Your Life
